import {
	CfnOutput,
	Duration,
	RemovalPolicy,
	Stack,
	type StackProps,
} from "aws-cdk-lib";
import {
	type ISecurityGroup,
	type IVpc,
	SubnetType,
} from "aws-cdk-lib/aws-ec2";
import { RetentionDays } from "aws-cdk-lib/aws-logs";
import {
	AuroraPostgresEngineVersion,
	ClusterInstance,
	Credentials,
	DatabaseCluster,
	DatabaseClusterEngine,
} from "aws-cdk-lib/aws-rds";
import { NagSuppressions } from "cdk-nag";
import type { Construct } from "constructs";

const createOutput = (scope: Construct, id: string, value: string): CfnOutput =>
	new CfnOutput(scope, id, { value });

export interface DataStackProps extends StackProps {
	readonly auroraMaxCapacity: number;
	readonly auroraMinCapacity: number;
	readonly bastionSecurityGroup: ISecurityGroup;
	readonly databaseName: string;
	readonly databaseUsername: string;
	readonly environmentName: "dev" | "prod";
	readonly projectName: string;
	readonly vpc: IVpc;
}

export class DataStack extends Stack {
	readonly cluster: DatabaseCluster;

	constructor(scope: Construct, id: string, props: DataStackProps) {
		super(scope, id, props);

		const isProduction = props.environmentName === "prod";
		const readers = isProduction
			? [
					ClusterInstance.serverlessV2("Reader", {
						enablePerformanceInsights: true,
						scaleWithWriter: true,
					}),
				]
			: undefined;

		this.cluster = new DatabaseCluster(this, "Database", {
			backup: {
				preferredWindow: "18:00-19:00",
				retention: Duration.days(isProduction ? 30 : 7),
			},
			cloudwatchLogsExports: ["postgresql"],
			cloudwatchLogsRetention: RetentionDays.ONE_MONTH,
			copyTagsToSnapshot: true,
			credentials: Credentials.fromUsername(props.databaseUsername),
			defaultDatabaseName: props.databaseName,
			deletionProtection: isProduction,
			engine: DatabaseClusterEngine.auroraPostgres({
				version: AuroraPostgresEngineVersion.VER_17_7,
			}),
			iamAuthentication: true,
			manageMasterUserPassword: true,
			readers,
			removalPolicy: isProduction
				? RemovalPolicy.RETAIN
				: RemovalPolicy.SNAPSHOT,
			serverlessV2MaxCapacity: props.auroraMaxCapacity,
			serverlessV2MinCapacity: props.auroraMinCapacity,
			storageEncrypted: true,
			vpc: props.vpc,
			vpcSubnets: { subnetType: SubnetType.PRIVATE_WITH_EGRESS },
			writer: ClusterInstance.serverlessV2("Writer", {
				enablePerformanceInsights: true,
			}),
		});
		this.cluster.connections.allowDefaultPortFrom(
			props.bastionSecurityGroup,
			"PostgreSQL through an authenticated SSM tunnel"
		);
		if (!isProduction) {
			NagSuppressions.addResourceSuppressions(this.cluster, [
				{
					id: "AwsSolutions-RDS10",
					reason:
						"The parallel dev cluster uses snapshot-on-delete so the learning environment can be removed without a protection toggle deployment.",
				},
			]);
		}

		const logRetentionProvider = this.node.tryFindChild(
			"LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a"
		);
		if (logRetentionProvider) {
			NagSuppressions.addResourceSuppressions(
				logRetentionProvider,
				[
					{
						appliesTo: [
							"Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
						],
						id: "AwsSolutions-IAM4",
						reason:
							"This singleton is generated by CDK only to enforce the requested RDS log retention period.",
					},
					{
						appliesTo: ["Resource::*"],
						id: "AwsSolutions-IAM5",
						reason:
							"The CDK log-retention provider manages the generated CloudWatch log group whose name is resolved at deployment.",
					},
				],
				true
			);
		}

		createOutput(
			this,
			"DatabaseEndpoint",
			this.cluster.clusterEndpoint.hostname
		);
		createOutput(
			this,
			"DatabaseSecretArn",
			this.cluster.secret?.secretArn ?? "secret-not-created"
		);

		this.templateOptions.description = `${props.projectName} ${props.environmentName} stateful data`;
	}
}
